In [3]:
import tensorflow as tf
import numpy as np

# Dataset: 4 gambar 64x64x3 acak dan 4 label
images = np.random.rand(4, 64, 64, 3)  # 4 gambar berukuran 64x64x3
labels = np.array([0, 1, 2, 3])  # 4 label acak (untuk klasifikasi 4 kelas)

# Mengonversi menjadi tf.data.Dataset
dataset = tf.data.Dataset.from_tensor_slices((images, labels))

# Menampilkan elemen pertama dari dataset
for image, label in dataset.take(1):
    print("Image shape:", image.shape)  # Menampilkan shape gambar
    print("Label:", label)  # Menampilkan label
for image, label in dataset.take(1):
    print("Image as array:", image.numpy())  # Menampilkan gambar sebagai array
    print("Label as array:", label.numpy())  # Menampilkan label sebagai array


Image shape: (64, 64, 3)
Label: tf.Tensor(0, shape=(), dtype=int64)
Image as array: [[[0.71937167 0.48129124 0.37526705]
  [0.56597639 0.78798226 0.3774896 ]
  [0.67397472 0.24220093 0.90171935]
  ...
  [0.3700494  0.90867508 0.35016296]
  [0.40409986 0.6895184  0.46574259]
  [0.10227931 0.16383836 0.96348319]]

 [[0.95023012 0.30598428 0.47165555]
  [0.37788718 0.73403739 0.01851544]
  [0.80178543 0.08295913 0.90784853]
  ...
  [0.82279933 0.0167704  0.89943731]
  [0.40696819 0.98601578 0.22166461]
  [0.33919289 0.97103756 0.95478054]]

 [[0.82221399 0.28567196 0.72410953]
  [0.29740517 0.50792715 0.25206978]
  [0.23910794 0.09690997 0.62783632]
  ...
  [0.40367566 0.14068555 0.94926358]
  [0.70418104 0.10509715 0.05004509]
  [0.71152621 0.09281637 0.7767704 ]]

 ...

 [[0.54436852 0.11609922 0.18787159]
  [0.69475869 0.65874124 0.47506339]
  [0.57730626 0.34777166 0.3810959 ]
  ...
  [0.17460023 0.0995418  0.85649052]
  [0.88969415 0.84832408 0.70271466]
  [0.82440603 0.47822003 0.55

2025-03-28 16:38:39.299092: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [5]:
import tensorflow as tf

# Fungsi generator yang menghasilkan data
def generate_data():
    for i in range(5):
        yield (i, i * 2)  # Menghasilkan pasangan (x, y)

# Mengonversi generator ke tf.data.Dataset dengan output_signature yang benar
dataset = tf.data.Dataset.from_generator(
    generate_data, 
    output_signature=(tf.TensorSpec(shape=(), dtype=tf.int32), tf.TensorSpec(shape=(), dtype=tf.int32))
)

# Menampilkan elemen pertama dari dataset
for x, y in dataset.take(1):
    print("x:", x.numpy(), "y:", y.numpy())


x: 0 y: 0
